name: Build
on:
  push:
    branches:
      - main
    paths:
      - '10/**'

permissions:
  contents: read

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend
      uses: docker/build-push-action@v3
      with:
        context: 10/frontend
        file: 10/frontend/Dockerfile
        push: true
        tags: docker.io/${{ secrets.DOCKER_USER }}/ebiznes-cloud-frontend:latest
        build-args: |
          VITE_API_URL=${{ secrets.API_URL }}

    - name: Build and push backend
      uses: docker/build-push-action@v3
      with:
        context: 10/backend
        file: 10/backend/Dockerfile
        push: true
        tags: docker.io/${{ secrets.DOCKER_USER }}/ebiznes-cloud-backend:latest

  send_email:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Build is finished
          body: Build of ${{ github.repository }} has been completed successfully. 
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}

  deploy_front:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: send_email
    environment:
      name: 'Deployment frontend'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy Azure webapp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ebiznes-cloud-frontend
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_f5e0b5d89b37400b86282bdf074c84af }}
          images: docker.io/${{ secrets.DOCKER_USER }}/ebiznes-cloud-frontend:latest

  deploy_backend:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: send_email
    environment:
      name: 'Deployment backend'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy Azure webapp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ebiznes-cloud-backend
          publish-profile: ${{ secrets.PUBLISH_PROFILE_BACKEND }}
          images: docker.io/${{ secrets.DOCKER_USER }}/ebiznes-cloud-backend:latest
