name: Build
on:
  push:
    branches:
      - main
    paths:
      - '10/**'

permissions:
  contents: read

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build and push frontend
      working-directory: 10/frontend
      run: |
        docker build --build-arg VITE_API_URL=${{ secrets.API_URL }} -t $DOCKER_USER/ebiznes-cloud-frontend .
        docker push $DOCKER_USER/ebiznes-cloud-frontend

    - name: Build and push backend
      working-directory: 10/backend
      run: |
        docker build -t $DOCKER_USER/ebiznes-cloud-backend .
        docker push $DOCKER_USER/ebiznes-cloud-backend

  send_email:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Build is finished
          body: Build of ${{ github.repository }} has been completed successfully. 
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}

  deploy_front:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: send_email
    environment:
      name: 'Deployment frontend'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy Azure webapp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ebiznes-cloud-frontend
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FRONTEND }}
          images: ${{ env.DOCKER_USER }}/ebiznes-cloud-frontend:latest

  deploy_backend:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: send_email
    environment:
      name: 'Deployment backend'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy Azure webapp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ebiznes-cloud-backend
          publish-profile: ${{ secrets.PUBLISH_PROFILE_BACKEND }}
          images: ${{ env.DOCKER_USER }}/ebiznes-cloud-backend:latest